kind: PersistentVolume
apiVersion: v1
metadata:
  name: ebs-pv
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
        volumeID: vol-0d976632465344fcc
        fsType: ext4